### PR TITLE
Fixing test cases 0004b and 0019b 

### PR DESCRIPTION
**Pull request by chrdebru**
0004b --> should not generate empty files
0019b --> should not generate files with partial results (being strict) as per discussion

### CODE REVIEW

**Comment by DylanVanAssche** [comment]
So we use no file as 'expect error' in the test cases? Just to be sure and to make it consistent across everything.
If that's the case, don't we need to do the same for invalid mappings, etc. testcases?

**Comment by chrdebru** [comment]
Yes. But these fixes are based on prior discussions in the issues. 00004b is an invalid mapping, and 0019b only contained successful triples ("best effort") and was thus inconsistent with other test cases yielding no result upon error.

**Comment by DylanVanAssche** [comment]
Yes, but I mean there are other testcases with invalid mappings, should we also update them to not have a mapping?

**Comment by DylanVanAssche** [comment]
Alright, we can fix them along the way, just wanted to make sure we're on the same page.

**Review by DylanVanAssche — APPROVED** [review]

**Pull request merged**
