### PR TITLE
Removing test 20b, which assumes an RML processor prepends generated terms that have a relative IRI with a (configurable) base IRI

### PR DESCRIPTION
**Pull request by chrdebru**
An RML engine should not normalize IRIs. The engine should check whether the generated value is an absolute IRI, or whether the base IRI + value constitutes an absolute IRI.

### CODE REVIEW

**Comment by DylanVanAssche** [comment]
Shouldn't we document this properly in the spec?

**Comment by bjdmeest** [comment]
yeah and then we break r2rml conformance, so should at least be discussed

**Comment by DylanVanAssche** [comment]
> break [r2rml conformance](https://www.w3.org/2001/sw/rdb2rdf/test-cases/#R2RMLTC0020b),

This test-case assumes data errors, which is checked by a R2RML validator. That part is optional in the spec of R2RML and RML.
It contradicts a bit with their own spec IMO. Needs discussion for sure.

> To obtain an absolute IRI from a relative IRI, the [term generation rules](https://www.w3.org/TR/r2rml/#dfn-term-generation-rules) of R2RML use simple string concatenation, rather than the more complex algorithm for resolution of relative URIs defined in [Section 5.2](http://tools.ietf.org/html/rfc3986#section-5.2) of [[RFC3986](https://www.w3.org/TR/r2rml/#RFC3986)]. This ensures that the original database value can be reconstructed from the generated absolute IRI.
...
> An [R2RML processor](https://www.w3.org/TR/r2rml/#dfn-r2rml-processor) MAY include an [R2RML data validator](https://www.w3.org/TR/r2rml/#dfn-r2rml-data-validator), but this is not required.

https://www.w3.org/TR/r2rml/

So in the new specification I'm all for to separate this much better. I agree with @chrdebru that a Processor should not do this, but a Validator should. 

> [Data errors](https://www.w3.org/TR/r2rml/#dfn-data-error) cannot generally be detected by analyzing the table schema of the database, but only by scanning the data in the tables. For large and rapidly changing databases, this can be impractical. Therefore, [R2RML processors](https://www.w3.org/TR/r2rml/#dfn-r2rml-processor) are allowed to answer queries that do not “touch” a data error, and the behavior of such operations is well-defined. For the same reason, the conformance of [R2RML mappings](https://www.w3.org/TR/r2rml/#dfn-r2rml-mapping) is defined without regard for the presence of data errors.
>
> [R2RML data validators](https://www.w3.org/TR/r2rml/#dfn-r2rml-data-validator) can be used to explicitly scan a database for data errors.

A bit further they go into detail about data errors where they distinguish it seems. This should come earlier in the spec IMO.

**Comment by bjdmeest** [comment]
I don't see the contradiction in R2RML: the engine only outputs elements that don't contain data errors, doesn't that comply with the sentence `Therefore, R2RML processors are allowed to answer queries that do not “touch” a data error`?

Should be clarified at least, specifically then that data errors in the case of IRI generation implies that the generation of IRI terms which result in non-valid IRIs result in NULL terms. (at least, that's how I interpret the current R2RML spec and test 20b)

Concerning the IRI normalization: this isn't actually normalization, it's 'just' prepending the @base in case of relative IRI generation (the spec specifically mentions that IRI resolution is out of scope). with rml:baseIRI we basically allow to override the default of using @base, but remain compatible with R2RML.

Do we have a specific reason not to allow prepending the @base in case of relative IRI terms @chrdebru ? Or do I misinterpret your PR?

**Comment by DylanVanAssche** [comment]
> I don't see the contradiction in R2RML: the engine only outputs elements that don't contain data errors.

They say that validation is optional (Validator is not included in a Processor), but require Processors then to 'validate'?
So if I don't do validation I comply as an implementation of a Processor with the spec, but fail the test-cases as they suddenly require validation to be included.

> specifically then that data errors in the case of IRI generation implies that the generation of IRI terms which result in non-valid IRIs result in NULL terms.

Problem remains that validation is optional so you cannot ask Processors to do this. If they fail to build an IRI, they can return `NULL`, but there will be data errors that still allow IRI generation.

> it's 'just' prepending the https://github.com/base in case of relative IRI generation (the spec specifically mentions that IRI resolution is out of scope). with rml:baseIRI we basically allow to override the default of using https://github.com/base, but remain compatible with R2RML.

We change this behavior compared to R2RML in the new spec with `rml:baseIRI`? I still see it as just taking the base IRI either from `@base` or from `rml:baseIRI` and then appending the relative IRI value to generate an absolute one. If that's valid, that's not a concern for the Processor.

**Comment by bjdmeest** [comment]
> When providing access to the [output dataset](https://www.w3.org/TR/r2rml/#dfn-output-dataset), an [R2RML processor](https://www.w3.org/TR/r2rml/#dfn-r2rml-processor) MUST abort any operation that requires inspecting or returning an [RDF term](https://www.w3.org/TR/r2rml/#dfn-rdf-term) whose generation would give rise to a [data error](https://www.w3.org/TR/r2rml/#dfn-data-error), and report an error to the agent invoking the operation.

**Comment by chrdebru** [comment]
> In summary for this PR: I'm fine with removing 20b for now, but only if we add 2 issues: (i) a clarification for the rml:baseIRI that takes this default behavior of using `@base` into account (which is an extension of R2RML, so I'm 👌 ), and (ii) an issue to discuss the requirement yes/no to only output valid RDF terms (which, if we say no, is in conflict wrt to R2RML, so I'm 👎 )

I just provided an example of why you cannot take `@base` into account. It was unintentionally confusing in R2RML's test cases to use the same base IRI for tests and input.

**Comment by DylanVanAssche** [comment]
Issues added, and we have a plan forward. Merging this.

**Pull request merged**
