### PR TITLE
fix shape based validation

### PR DESCRIPTION
**Pull request by pmaria**

### CODE REVIEW

**Comment by pmaria** [comment]
This change breaks the excessively long chain of `sh:node` statements in the shape leading to recursion issues in pyshacl.
In essence most of the `sh:node` statements in the shapes could be removed, since this is also covered by `sh:targetObjectsOf` of the object.

So, if we have:

```turtle
:x
 sh:path :y ;
 sh:node :z .

:z sh:targetObjectsOf :y .
``` 

we can omit `:x sh:node :z`.

I now only made a minimal change by removing one sh:node statement. But IMO we could remove all of them that match the above.
@DylanVanAssche what is your opinion on this?

**Comment by DylanVanAssche** [comment]
If the removals are not punching holes in the coverage I'm all for it!
Basically, we must be able to validate via 2 ways:

1. Property paths
2. RDF type classes

**Comment by pmaria** [comment]
Ok, then I will remove those `sh:node` statements that aren't necessary for this.

**Review by DylanVanAssche — APPROVED** [review]
Looks fine to me.

**Pull request merged**
